"""SpikeGPT reproduction built on the myelin SNN library.

Core spiking-neuron kernels, surrogates, packing, and hardware export live in
the ``myelin`` package (a dependency). This package adds the SpikeGPT/RWKV
language model, the fused WKV recurrence, the token corpus, and spike
statistics for the enwik8/WikiText reproductions.
"""

from spikegpt.language import (
    SPIKEGPT_PRESETS,
    AttentionKind,
    BPEVocabulary,
    ByteVocabulary,
    CharacterVocabulary,
    LanguageEval,
    LanguageVocabulary,
    SamplingMode,
    SpikeChannelMix,
    SpikeChannelMixState,
    SpikeGPTBlock,
    SpikeGPTBlockState,
    SpikeGPTConfig,
    SpikeGPTModelType,
    SpikeGPTPreset,
    SpikeGPTPresetSpec,
    SpikeLanguageCheckpoint,
    SpikeLanguageModel,
    SpikeLanguageModelState,
    SpikeTimeMix,
    SpikeTimeMixState,
    SpikingSequenceLIF,
    SpikingSequenceLIFState,
    VanillaAttentionMix,
    VanillaAttentionState,
    evaluate_language_model,
    evaluate_language_model_strided,
    language_vocabulary_from_dict,
    language_vocabulary_to_dict,
    load_spike_language_checkpoint,
    sample_token_batch,
    save_spike_language_checkpoint,
    spikegpt_config_from_dict,
    spikegpt_config_from_preset,
    spikegpt_config_to_dict,
    split_token_sequence,
    split_train_val_test,
    weighted_key_value,
    weighted_key_value_loop,
)
from spikegpt.spike_statistics import (
    PopulationSpikeStats,
    SpikeStatistics,
    SpikingFractionReport,
    collect_spike_statistics,
    compute_spiking_fraction,
    format_spike_report,
)
from spikegpt.token_corpus import MemmapTokenCorpus, TokenArrayView, TokenCorpusWriter

__all__ = [
    "SPIKEGPT_PRESETS",
    "BPEVocabulary",
    "ByteVocabulary",
    "CharacterVocabulary",
    "LanguageEval",
    "LanguageVocabulary",
    "SamplingMode",
    "SpikeChannelMix",
    "SpikeChannelMixState",
    "SpikeGPTBlock",
    "SpikeGPTBlockState",
    "SpikeGPTConfig",
    "AttentionKind",
    "SpikeGPTModelType",
    "SpikeGPTPreset",
    "SpikeGPTPresetSpec",
    "SpikeLanguageCheckpoint",
    "SpikeLanguageModel",
    "VanillaAttentionMix",
    "VanillaAttentionState",
    "SpikeLanguageModelState",
    "SpikeTimeMix",
    "SpikeTimeMixState",
    "SpikingSequenceLIF",
    "SpikingSequenceLIFState",
    "evaluate_language_model",
    "evaluate_language_model_strided",
    "language_vocabulary_from_dict",
    "language_vocabulary_to_dict",
    "load_spike_language_checkpoint",
    "sample_token_batch",
    "save_spike_language_checkpoint",
    "spikegpt_config_from_dict",
    "spikegpt_config_from_preset",
    "spikegpt_config_to_dict",
    "split_token_sequence",
    "split_train_val_test",
    "weighted_key_value",
    "weighted_key_value_loop",
    "PopulationSpikeStats",
    "SpikeStatistics",
    "SpikingFractionReport",
    "collect_spike_statistics",
    "compute_spiking_fraction",
    "format_spike_report",
    "MemmapTokenCorpus",
    "TokenArrayView",
    "TokenCorpusWriter",
]
